Repository strongbox/strongbox, pull requests merged in 2019-06, with the labels that each got.

#1320 Fixing issues with `ArtifactEntryServiceTest.deleteButNotAllShouldWork() `
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java
Labels: ready

#1314 Issue-1300: CronTaskConfigurationDto should base on java.util.UUID not on java.lang.String
  strongbox-commons/pom.xml
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/domain/CronTaskConfiguration.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/domain/CronTaskConfigurationDto.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/jobs/AbstractCronJob.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/CronJobSchedulerService.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/CronTaskConfigurationService.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/CronTaskDataService.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/impl/CronJobSchedulerServiceImpl.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/impl/CronTaskConfigurationServiceImpl.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/impl/CronTaskDataServiceImpl.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/event/cron/CronTaskEventListenerRegistry.java
  strongbox-cron/strongbox-cron-tasks/src/test/java/org/carlspring/strongbox/cron/jobs/BaseCronTestCase.java
  strongbox-cron/strongbox-cron-tasks/src/test/java/org/carlspring/strongbox/cron/jobs/ImmediateExecutionCronJobTestIT.java
  strongbox-cron/strongbox-cron-tasks/src/test/java/org/carlspring/strongbox/cron/jobs/OneTimeExecutionCronJobTestIT.java
  strongbox-security/strongbox-authentication-registry/pom.xml
  strongbox-security/strongbox-user-management/pom.xml
  strongbox-storage/strongbox-storage-api/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/BaseCronJobWithMavenIndexingTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/CleanupExpiredArtifactsFromProxyRepositoriesCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/ClearTrashCronJobFromMaven2RepositoryTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/DownloadRemoteMavenIndexCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RebuildMavenIndexesCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RebuildMavenMetadataCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RegenerateMavenChecksumCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RemoveTimestampedMavenSnapshotCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/FetchChangesFeedCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/BaseCronJobWithNugetIndexingTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RegenerateNugetChecksumCronJobTestIT.java
  strongbox-web-core/pom.xml
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/cron/CronTaskController.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/cron/CronTaskControllerTest.java
Labels: ready

#1325 issue-1301 Create an NpmTestRepository annotation
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NpmTestRepository.java
Labels: in progress

#1290 Issue-528: HandlerMethodArgumentResolver to resolve Repository instance based on `{storageId}/{repositoryId}` path variables
  strongbox-web-core/src/main/java/org/carlspring/strongbox/config/WebConfig.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BrowseController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/DefaultExceptionHandler.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/TrashController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/ArtifactCoordinateValidatorsManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/maven/MavenArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/maven/MavenMetadataManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/raw/RawArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/exception/RepositoryNotFoundException.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/exception/ServiceUnavailableException.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/exception/StorageNotFoundException.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/ArtifactCoordinateValidatorsManagementControllerTest.java
Labels: ready

#1326 Issue-1303: Create a NugetTestRepository annotation
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NugetTestRepository.java
Labels: ready

#1336 SB-1254: Logback configuration improvements
  pom.xml
  strongbox-aql/pom.xml
  strongbox-client/pom.xml
  strongbox-commons/pom.xml
  strongbox-commons/src/main/java/org/carlspring/strongbox/log/CronTaskContextAcceptFilter.java
  strongbox-commons/src/main/java/org/carlspring/strongbox/log/CronTaskContextDeclineFilter.java
  strongbox-commons/src/main/resources/application.yaml
  strongbox-configuration/pom.xml
  strongbox-cron/strongbox-cron-api/pom.xml
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/impl/CronJobSchedulerServiceImpl.java
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/impl/CronTaskExecutor.java
  strongbox-cron/strongbox-cron-tasks/pom.xml
  strongbox-data-service/pom.xml
  strongbox-distribution/pom.xml
  strongbox-distribution/src/main/resources/setenv.conf
  strongbox-event-api/pom.xml
  strongbox-resources/strongbox-common-resources/pom.xml
  strongbox-resources/strongbox-common-resources/src/main/resources/logback-spring-debug.xml
  strongbox-resources/strongbox-common-resources/src/main/resources/logback-spring.xml
  strongbox-security/strongbox-authentication-api/pom.xml
  strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/pom.xml
  strongbox-security/strongbox-authentication-registry/pom.xml
  strongbox-security/strongbox-authentication-support/pom.xml
  strongbox-security/strongbox-security-api/pom.xml
  strongbox-security/strongbox-user-management/pom.xml
  strongbox-storage/strongbox-storage-api/pom.xml
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/storage/repository/remote/heartbeat/RemoteRepositoriesHeartbeatMonitorInitiator.java
  strongbox-storage/strongbox-storage-core/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/config/Maven2LayoutProviderTestConfig.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/BaseCronJobWithMavenIndexingTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/DownloadRemoteMavenIndexCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RebuildMavenIndexesCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/resources/maven-test.properties
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-p2-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-raw-layout-provider/pom.xml
  strongbox-testing/strongbox-testing-core/pom.xml
  strongbox-testing/strongbox-testing-storage/pom.xml
  strongbox-testing/strongbox-testing-web/pom.xml
  strongbox-web-core/pom.xml
  strongbox-web-forms/pom.xml
Labels: ready

#1338 Issue-1295: Make the NugetArtifactGenerator implement the ArtifactGenerator interface
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/artifact/coordinates/NugetArtifactConverterTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NugetArtifactGenerator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/BaseCronJobWithNugetIndexingTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RegenerateNugetChecksumCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/nuget/filter/NugetFilterODataParserTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/NugetGroupRepositoryProviderTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/TempNupkgFileTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/rss/PackageFeedTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/TestCaseWithNugetArtifactGeneration.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/NugetRestAssuredBaseTest.java
Labels: ready

#1324 issue-1322: Drop maven-commons
  strongbox-aql/pom.xml
  strongbox-client/pom.xml
  strongbox-configuration/pom.xml
  strongbox-cron/strongbox-cron-api/pom.xml
  strongbox-cron/strongbox-cron-tasks/pom.xml
  strongbox-distribution/pom.xml
  strongbox-security/strongbox-authentication-support/pom.xml
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/artifact/coordinates/MockedMavenArtifactCoordinates.java
  strongbox-storage/strongbox-storage-core/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api/src/main/java/org/carlspring/strongbox/storage/metadata/MetadataHelper.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api/src/main/java/org/carlspring/strongbox/storage/metadata/MetadataMerger.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api/src/main/java/org/carlspring/strongbox/storage/metadata/SnapshotVersionDecomposition.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api/src/main/java/org/carlspring/strongbox/storage/metadata/VersionCollector.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/artifact/MavenArtifactUtils.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/artifact/MavenRepositoryArtifact.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/artifact/coordinates/MavenArtifactCoordinates.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/locator/handlers/RemoveTimestampedSnapshotOperation.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/Maven2FileSystemProvider.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/Maven2LayoutProvider.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/services/impl/ArtifactMetadataServiceImpl.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/MavenMetadataManager.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/MavenSnapshotManager.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/validation/version/MavenVersionValidator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/artifact/coordinates/MavenArtifactCoordinatesTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generation/MavenArtifactGeneratorTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/MavenArtifactDeployer.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/MavenArtifactGenerator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RegenerateMavenChecksumCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RemoveTimestampedMavenSnapshotCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/dependency/snippet/BazelDependencyFormatterTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/io/ArtifactOutputStreamTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/io/BaseMavenMetadataExpirationTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/ParallelDownloadRemoteArtifactTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/RetryDownloadArtifactWithPermanentFailureStartingAtSomePointTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/RetryDownloadArtifactWithSingleFailureAtSomePointTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/RetryDownloadArtifactWithUnsupportedRangeRequestTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactMetadataServiceReleasesTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactMetadataServiceSnapshotsTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/storage/validation/version/MavenReleaseVersionValidatorTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/storage/validation/version/MavenSnapshotVersionValidatorTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/MavenTestCaseWithArtifactGeneration.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/artifact/MavenArtifactGeneratorStrategy.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/artifact/MavenArtifactTestUtils.java
  strongbox-testing/strongbox-testing-core/pom.xml
  strongbox-testing/strongbox-testing-storage/pom.xml
  strongbox-web-core/pom.xml
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/maven/MavenMetadataManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/interceptors/MavenArtifactRequestInterceptor.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/cron/CronTaskControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/maven/MavenArtifactControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/MavenRestAssuredBaseTest.java
Labels: enhancement, ready

#1331 issue-1165 BaseMavenGroupRepositoryComponentTest tests migration
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/BaseMavenGroupRepositoryComponentTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/index/MavenIndexGroupRepositoryComponentOnCreateTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/index/MavenIndexGroupRepositoryComponentOnDeleteTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnAddTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnDeleteTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnUploadTest.java
Labels: ready
