Repository strongbox/strongbox, pull requests merged in 2019-05, with the labels that each got.

#1265 Added validation for OPTIONS request on entryPoint
  strongbox-web-core/src/main/java/org/carlspring/strongbox/security/authentication/Http401AuthenticationEntryPoint.java
Labels: expecting-icla, ready

#1269 Custom MVC mapping annotation for Artifact Controllers
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/configuration/ConfigurationManager.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/configuration/StoragesConfigurationManager.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/providers/header/HeaderMappingRegistry.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/Maven2LayoutProvider.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/NpmLayoutProvider.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/NugetLayoutProvider.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-raw-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/RawLayoutProvider.java
  strongbox-testing/strongbox-testing-web/src/test/java/org/carlspring/strongbox/config/RestAssuredConfig.java
  strongbox-testing/strongbox-testing-web/src/test/java/org/carlspring/strongbox/rest/common/RestAssuredBaseTest.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/config/WebConfig.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/maven/MavenArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/raw/RawArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/CustomRequestMappingHandlerMapping.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/HeaderMappingFilter.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/LayoutRequestCondition.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/LayoutRequestMapping.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/config/IntegrationTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/AccountControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/security/authentication/AuthenticatorsConfigControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/cron/CronTaskControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/MavenRestAssuredBaseTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/NpmRestAssuredBaseTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/NugetRestAssuredBaseTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/RawRestAssuredBaseTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/web/LayoutRequestMappingTest.java
  strongbox-web-core/src/test/resources/application-test.properties
Labels: ready

#1276 Issue 1270: Add Bazel dependency formatter for Maven artifacts
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/dependency/snippet/BazelDependencyFormatter.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/dependency/snippet/BazelDependencyFormatterTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/dependency/snippet/MavenDependencyFormatterTest.java
Labels: in progress

#1283 Issue-1167: Replace application.properties by yaml equivalent.
  strongbox-commons/src/main/resources/application.properties
  strongbox-commons/src/main/resources/application.yaml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/resources/application-test.properties
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/resources/application-test.yaml
  strongbox-web-core/src/test/resources/application-test.properties
  strongbox-web-core/src/test/resources/application-test.yaml
Labels: ready

#1287 Issue-1286: Fix typo in the UiController
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/UiController.java
Labels: ready

#1272 SB-1325 Proxy artifact resolution issue - minimizing risk
  strongbox-web-core/src/main/java/org/carlspring/strongbox/config/WebConfig.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BrowseController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/LoggingManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/PingController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/TrashController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/security/authorization/AuthorizationConfigController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/environment/EnvironmentInfoController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/maven/MavenArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/maven/MavenMetadataManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/raw/RawArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/interceptors/ArtifactRequestInterceptor.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/interceptors/MavenArtifactRequestInterceptor.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/interceptors/RepositoryRequestInterceptor.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/security/CustomAccessDeniedHandler.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/security/authentication/Http401AuthenticationEntryPoint.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/security/authentication/suppliers/NugetApiKeyAuthenticationSupplier.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/security/vote/ExtendedAuthoritiesVoter.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/Constants.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/CustomRequestMappingHandlerMapping.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/ExposableRequestCondition.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/LayoutRequestCondition.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/LayoutRequestMapping.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryNotFoundRequestCondition.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryRequestCondition.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/ResponseAlreadyCommittedException.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/web/StorageNotFoundRequestCondition.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/maven/MavenArtifactControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/security/CustomAccessDeniedHandlerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/web/LayoutRequestMappingTest.java
Labels: ready

#1296 Issue 1262: Cleanup our dependency tree and make sure we have no dependencies on commons-collections 3.x
  strongbox-security/strongbox-authentication-registry/pom.xml
  strongbox-security/strongbox-authentication-registry/src/main/java/org/carlspring/strongbox/authentication/registry/support/ExternalAuthenticatorsHelper.java
  strongbox-security/strongbox-user-management/pom.xml
  strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/dto/UsersDto.java
  strongbox-storage/strongbox-storage-api/pom.xml
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/group/GroupRepositorySetCollector.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/proxied/LocalStorageProxyRepositoryExpiredArtifactsCleaner.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceImpl.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/ConfigurationManagementServiceImpl.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/search/MavenIndexerSearchProvider.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/repository/group/BaseMavenGroupRepositoryComponent.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/indexing/RepositoryIndexer.java
  strongbox-web-core/pom.xml
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/ServerConfigurationController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/cron/CronTaskController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/converters/cron/CronTaskConfigurationFormToCronTaskConfigurationDtoConverter.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/converters/users/AccessModelToAccessModelOutputConverter.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/users/UserControllerTestIT.java
Labels: ready

#1293 Issues/1292: Implemented `@RepositoryAttributes` annotation
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/io/StorageFileSystemProvider.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/layout/LayoutFileSystemProvider.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/RepositoryAttributes.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/RepositoryManagementTestExecutionListener.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementApplicationContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementContext.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/ClearTrashCronJobFromMaven2RepositoryTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/MavenRepositorySetup.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/artifact/MavenTestArtifact.java
Labels: ready

#1266 issues-1248: ArtifactManagementServiceImplTest.testConcurrentReadWrite
  strongbox-aql/src/main/java/org/carlspring/strongbox/services/impl/AqlSearchServiceImpl.java
  strongbox-client/src/main/java/org/carlspring/strongbox/client/RestArtifactResolver.java
  strongbox-commons/src/main/java/org/carlspring/strongbox/io/StreamUtils.java
  strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/artifact/ArtifactNotFoundException.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/artifact/AsyncArtifactEntryHandler.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/io/AbstractRepositoryProvider.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/io/RepositoryPathLock.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/io/RepositoryStreamSupport.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/io/StorageFileSystemProvider.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/layout/LayoutFileSystemProvider.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/HostedRepositoryProvider.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/search/AbstractSearchProvider.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/ArtifactManagementService.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/ArtifactResolutionServiceImpl.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/support/ArtifactStoredEventListener.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/configuration/ConfigurationManagerTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ConfigurationManagementServiceImplTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/repository/NullRepository.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryContext.java
  strongbox-storage/strongbox-storage-api/src/test/resources/junit-platform.properties
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/io/LazyInputStream.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/io/LazyOutputStream.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RegenerateMavenChecksumCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/io/ArtifactOutputStreamTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/MockedRestArtifactResolverTestBase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/ParallelDownloadRemoteArtifactTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/RetryDownloadArtifactTestBase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/RetryDownloadArtifactWithPermanentFailureStartingAtSomePointTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/RetryDownloadArtifactWithSingleFailureAtSomePointTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/RetryDownloadArtifactWithUnsupportedRangeRequestTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnUploadTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactMetadataServiceSnapshotsTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/MavenChecksumServiceTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/resources/junit-platform.properties
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/resources/junit-platform.properties
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/junit-platform.properties
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseController.java
Labels: ready
