Repository strongbox/strongbox, pull requests merged in 2019-10, with the labels that each got.

#1505 Implement PyPi package distribution metadata validation #1179
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/main/java/org/carlspring/strongbox/domain/PypiPackageInfo.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/main/java/org/carlspring/strongbox/util/PypiMetadataParser.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/main/java/org/carlspring/strongbox/util/PypiPackageInfoValidator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/test/java/org/carlspring/strongbox/util/PypiMetadataParserTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/test/resources/org.carlspring.strongbox.util/PKG-INFO
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/test/resources/org.carlspring.strongbox.util/PKG-INFO-empty-values
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/test/resources/org.carlspring.strongbox.util/PKG-INFO-invalid-metadata-version
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/test/resources/org.carlspring.strongbox.util/PKG-INFO-invalid-name
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/test/resources/org.carlspring.strongbox.util/PKG-INFO-invalid-version
Labels: ready

#1504 Issue-1475: Test that ArtifactEntity properties created, lastUpdated, lastUsed retain time when saved and read to/from db
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java
Labels: ready

#1530 issue-1527 Allow passing token via cookie
  strongbox-web-core/src/main/java/org/carlspring/strongbox/security/authentication/JwtTokenFetcher.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/security/authentication/suppliers/JWTAuthenticationSupplier.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java
Labels: ready

#1516 issue-1169: Use SpringBoot "@Value + Resource" to load YAML resources.
  strongbox-commons/pom.xml
  strongbox-commons/src/main/java/org/carlspring/strongbox/config/CommonConfig.java
  strongbox-commons/src/main/java/org/carlspring/strongbox/config/PropertiesPathResolverConfig.java
  strongbox-commons/src/test/java/org/carlspring/strongbox/config/PropertiesPathResolverConfigTest.java
  strongbox-configuration/src/main/java/org/carlspring/strongbox/yaml/YamlFileManager.java
  strongbox-cron/strongbox-cron-api/pom.xml
  strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/config/CronTasksConfigurationFileManager.java
  strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/pom.xml
  strongbox-security/strongbox-authentication-registry/pom.xml
  strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/authorization/AuthorizationConfigFileManager.java
  strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/UsersFileManager.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/configuration/ConfigurationFileManager.java
  strongbox-testing/strongbox-testing-core/pom.xml
  strongbox-testing/strongbox-testing-core/src/main/java/org/carlspring/strongbox/config/AutomaticTestPropertiesEnvironmentPostProcessor.java
  strongbox-testing/strongbox-testing-core/src/main/resources/META-INF/spring.factories
Labels: being reviewed, ready

#1525 SB-1423: Authentication fails when concurrent requests to protected endpoints occur
  strongbox-data-service/src/main/java/org/carlspring/strongbox/data/domain/GenericEntity.java
  strongbox-security/strongbox-authentication-registry/src/main/java/org/carlspring/strongbox/authentication/AuthenticationConfig.java
  strongbox-security/strongbox-authentication-registry/src/main/java/org/carlspring/strongbox/authentication/ConfigurableProviderManager.java
  strongbox-security/strongbox-authentication-registry/src/main/java/org/carlspring/strongbox/authentication/OrientDbExternalUsersCacheManager.java
  strongbox-security/strongbox-authentication-registry/src/test/java/org/carlspring/strongbox/authentication/ConfigurableProviderManagerTest.java
  strongbox-security/strongbox-authentication-registry/src/test/java/org/carlspring/strongbox/authentication/JwtAuthenticationProviderTest.java
  strongbox-security/strongbox-authentication-registry/src/test/resources/etc/conf/eudst-strongbox-security-users.yaml
  strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/service/UserAlreadyExistsException.java
  strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/service/UserEntryService.java
  strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/service/impl/OrientDbUserService.java
  strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/userdetails/SpringSecurityUser.java
  strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/userdetails/UserDetailsMapper.java
Labels: ready

#1548 Added a sponsors section
  README.md
Labels: ready

#1492 Issue 1487 Drop TempDirBooter and Tmp related code
  strongbox-commons/pom.xml
  strongbox-commons/src/main/java/org/carlspring/strongbox/booters/PropertiesBooter.java
  strongbox-commons/src/main/java/org/carlspring/strongbox/booters/TempDirBooter.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/config/StorageApiConfig.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/maven/MavenArtifactControllerTest.java
Labels: ready

#1486 Issue 1169: Simplify ConfigurationResourceResolver and YamlFileManager
  strongbox-commons/src/main/java/org/carlspring/strongbox/booters/PropertiesBooter.java
  strongbox-commons/src/main/java/org/carlspring/strongbox/booters/TempDirBooter.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/app/StrongboxSpringBootApplication.java
Labels: being reviewed
