Repository strongbox/strongbox, pull requests merged in 2019-08, with the labels that each got.

#1415 issues/1413: StoragesConfigurationControllerSmokeTest
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/io/LayoutFileSystem.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/io/StorageFileSystem.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationControllerSmokeTest.java
Labels: ready

#1416 Issue-1328: Migrate the NPM layout provider tests to use the new annotations
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/coordinates/NpmArtifactCoordinatesTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/coordinates/NpmArtifactCoorinatesTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NpmArtifactGenerator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/BaseCronJobWithNpmIndexingTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/FetchChangesFeedCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/dependency/snippet/NpmDependencyFormatterTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/NpmReplicateUrlRepositorySetup.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/NpmRepositoryTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/artifact/NpmTestArtifact.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NpmRepository.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/NpmRestAssuredBaseTest.java
Labels: in progress

#1405 Issue-1327: Migrate the NuGet layout provider tests to use the new annotations.
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/artifact/coordinates/NugetArtifactCoordinates.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/artifact/coordinates/NugetArtifactConverterTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NugetArtifactGenerator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/config/NugetBootersTestConfig.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/BaseCronJobWithNugetIndexingTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RegenerateNugetChecksumCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/dependency/snippet/NugetDependencyFormatterTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/nuget/filter/NugetFilterODataParserTestCase.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/NugetGroupRepositoryProviderTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/indexing/NugetRemoteRepositoryTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/TempNupkgFileTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/rss/PackageFeedTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/TestCaseWithNugetArtifactGeneration.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/artifact/NugetArtifactGeneratorStrategy.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/artifact/NugetTestArtifact.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/NugetRestAssuredBaseTest.java
Labels: ready

#1426 issues/1423: NpmArtifactControllerTest fixed + Test repository management cleanup
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NpmArtifactGenerator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/artifact/NpmArtifactGeneratorStrategy.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/artifact/NpmTestArtifact.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/NpmRestAssuredBaseTest.java
Labels: ready

#1439 Issue-1438: Fix language-related error for testJWTAuthShouldFailWithoutToken test.
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java
Labels: ready

#1435 Move from delays to checksums on two tests to work around timestamp granularity on MacOS JRE
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/storage/indexing/local/RepositoryHostedIndexCreatorTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/maven/MavenIndexControllerTest.java
Labels: ready

#1449 Hotfix: Fix compilation failure in strongbox-cron-api.
  strongbox-cron/strongbox-cron-api/pom.xml
Labels: bug

#1453 Hotfix: Disable tests parallelization in strongbox-storage-api.
  strongbox-storage/strongbox-storage-api/src/test/resources/junit-platform.properties
Labels: bug
