Repository strongbox/strongbox, pull requests merged in 2019-03, with the labels that each got.

#1081 Issue-1072: Enable metrics, scheduledtasks, shutdown, threaddump and Spring Boot Actuators
  strongbox-commons/src/main/resources/application.properties
  strongbox-web-core/src/main/java/org/carlspring/strongbox/app/StrongboxSpringBootApplication.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/restart/RestartController.java
Labels: ready

#1075 SB-1360 pattern for storageId and repositoryId
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/forms/configuration/RepositoryFormTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/forms/configuration/StorageFormTestIT.java
  strongbox-web-forms/src/main/java/org/carlspring/strongbox/forms/configuration/RepositoryForm.java
  strongbox-web-forms/src/main/java/org/carlspring/strongbox/forms/configuration/StorageForm.java
Labels: ready

#1091 issue-1090 CronTaskControllerTest close the stream
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/cron/CronTaskControllerTest.java
Labels: ready

#1095 issue-1090 using mocked instance of CronJobSchedulerService in s-w-c …
  strongbox-web-core/src/test/java/org/carlspring/strongbox/config/IntegrationTest.java
Labels: ready

#1082 Issue-1071: Expose versioning information using Spring Boot Actuator
  strongbox-commons/pom.xml
  strongbox-commons/src/main/java/org/carlspring/strongbox/booters/PropertiesBooter.java
  strongbox-commons/src/main/resources/application.properties
  strongbox-web-core/src/main/java/org/carlspring/strongbox/actuator/StrongboxCustomInfo.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/config/WebConfig.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/ActuatorEndpointControllerTest.java
Labels: ready

#1078 SB-1360 routing rules improvements
  strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox.xml
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/GroupRepositoryProvider.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/ConfigurationManagementServiceImpl.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/support/ArtifactRoutingRulesChecker.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/configuration/ConfigurationManagerTest.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/services/ConfigurationManagementService.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/MutableRoutingRule.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/MutableRoutingRuleRepository.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/MutableRoutingRules.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/MutableRuleSet.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/RepositoryIdentifiable.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/RoutingRule.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/RoutingRuleRepository.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/RoutingRuleTypeEnum.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/RoutingRules.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/routing/RuleSet.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/xml/RuleSetMap.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/xml/RuleSetMapAdapter.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/io/MavenGroupRepositoryPathFetchEventListener.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/repository/group/BaseMavenGroupRepositoryComponent.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/MavenGroupRepositoryProviderTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/index/MavenIndexGroupRepositoryComponentOnCreateTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/index/MavenIndexGroupRepositoryComponentOnDeleteTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnAddTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnDeleteTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnUploadTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ConfigurationManagementServiceImplTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/TestCaseWithMavenArtifactGenerationAndIndexing.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/config/WebConfig.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/RoutingConfigurationController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/converters/storage/routing/RoutingRuleFormToMutableConverter.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/converters/storage/routing/RoutingRuleFormToRoutingRuleConverter.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/converters/storage/routing/RuleSetFormToRuleSetConverter.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/RoutingConfigurationControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/forms/storage/routing/RoutingRuleFormTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/forms/storage/routing/RuleSetFormTestIT.java
  strongbox-web-core/src/test/resources/etc/conf/strongbox.xml
  strongbox-web-forms/src/main/java/org/carlspring/strongbox/forms/storage/routing/RoutingRuleForm.java
  strongbox-web-forms/src/main/java/org/carlspring/strongbox/forms/storage/routing/RoutingRuleRepositoryForm.java
  strongbox-web-forms/src/main/java/org/carlspring/strongbox/forms/storage/routing/RuleSetForm.java
Labels: ready

#1114 Issue-1016: Update all junit-jupiter dependencies to use new dependency-aggregating artifact
  strongbox-aql/pom.xml
  strongbox-client/pom.xml
  strongbox-commons/pom.xml
  strongbox-configuration/pom.xml
  strongbox-cron/strongbox-cron-tasks/pom.xml
  strongbox-event-api/pom.xml
  strongbox-resources/strongbox-common-resources/pom.xml
  strongbox-rest-client/pom.xml
  strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/pom.xml
  strongbox-security/strongbox-authentication-registry/pom.xml
  strongbox-security/strongbox-authentication-support/pom.xml
  strongbox-security/strongbox-security-api/pom.xml
  strongbox-security/strongbox-user-management/pom.xml
  strongbox-storage/strongbox-storage-api/pom.xml
  strongbox-storage/strongbox-storage-core/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-p2-layout-provider/pom.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-raw-layout-provider/pom.xml
  strongbox-testing/strongbox-testing-core/pom.xml
  strongbox-testing/strongbox-testing-storage/pom.xml
  strongbox-testing/strongbox-testing-web/pom.xml
  strongbox-web-core/pom.xml
Labels: ready

#1106 Issue 611 exclude jnuget
  CONTRIBUTING.md
  strongbox-commons/src/main/java/org/carlspring/strongbox/booters/TempDirBooter.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/booters/StorageBooter.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/config/StorageApiConfig.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/NugetFormatException.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/NugetNamespaceFilter.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/Nuspec.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/Reference.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/TempNupkgFile.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/AssemblyTargetFrameworkAdapter.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/ContentFile.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/Dependencies.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/DependenciesGroup.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/Dependency.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/File.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/Framework.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/FrameworkAssembly.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/PackageType.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/Repository.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/StringListTypeAdapter.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/VersionRange.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/VersionTypeAdapter.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NugetPackageGenerator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/config/NugetBootersTestConfig.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/RegenerateNugetChecksumCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/NugetGroupRepositoryProviderTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/NugetTestResourceUtil.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/NuspecTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/TempNupkgFileTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/DependenciesGroupTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/DependencyTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/FrameworkAssemblyTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/FrameworksTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/NugetNamespaceFilterTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/storage/metadata/nuget/metadata/VersionRangeTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/TestCaseWithNugetPackageGeneration.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/DockPanelSuite.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/Extended.Wpf.Toolkit.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/FluentAssertions.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/NHibernate.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/NLog.nuspec.2.0.1.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/NLog.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/NUnit.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/PostSharp.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/Spring.Data.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/fixed.dependency.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/group.dependencies.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/incorrect.version.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/test.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/v3/Package.v3.nuspec.xml
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/resources/org/carlspring/strongbox/storage/metadata/nuget/nuspec/v3/Package.with.files.nuspec.xml
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java
Labels: in progress

#1105 TestRepository annotation support
  strongbox-resources/strongbox-common-resources/src/main/resources/logback-spring-debug.xml
  strongbox-resources/strongbox-common-resources/src/main/resources/logback-spring.xml
  strongbox-rest-client/src/main/java/org/carlspring/strongbox/client/RestClient.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/artifact/coordinates/NullArtifactCoordinates.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/proxied/LocalStorageProxyRepositoryExpiredArtifactsCleaner.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/proxied/ProxyRepositoryArtifactResolver.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/support/RepositoryCreatedEventListener.java
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/storage/repository/remote/heartbeat/RemoteRepositoriesHeartbeatMonitorInitiator.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/StorageApiTestConfig.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/providers/io/RepositoryPathTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/providers/layout/AbstractLayoutProviderTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/storage/repository/RepositoryManagementTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/storage/validation/version/GenericReleaseVersionValidatorTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/storage/validation/version/GenericSnapshotVersionValidatorTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/NullFileSystem.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/NullFileSystemProvider.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/NullLayoutConfiguration.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/NullLayoutProvider.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/NullRepositoryManagementStrategy.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/TestCaseWithRepositoryManagement.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/RepositoryManagementTestExecutionListener.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepository.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementApplicationContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementContext.java
  strongbox-storage/strongbox-storage-api/src/test/resources/junit-platform.properties
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/configuration/Configuration.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/RepositoryArrayToMapJsonDeserializer.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/Storage.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/repository/ImmutableRepository.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/storage/repository/Repository.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/event/artifact/MavenArtifactFetchedFromRemoteEventListener.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/io/MavenMetadataExpiredRepositoryPathHandler.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/repository/IndexedMavenRepositoryFeatures.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/services/impl/ArtifactIndexesServiceImpl.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/indexing/RepositoryIndexerFactory.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/indexing/downloader/IndexDownloadRequest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/ClearTrashCronJobFromMaven2RepositoryTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/io/MavenMetadataExpirationProxyCaseTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/index/BaseMavenIndexGroupRepositoryComponentTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/index/MavenIndexGroupRepositoryComponentOnCreateTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/index/MavenIndexGroupRepositoryComponentOnDeleteTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnAddTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnDeleteTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/repository/group/metadata/MavenMetadataGroupRepositoryComponentOnUploadTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/storage/indexing/downloader/MockedIndexResourceFetcher.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/storage/validation/version/MavenReleaseVersionValidatorTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/storage/validation/version/MavenSnapshotVersionValidatorTest.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/TestCaseWithMavenArtifactGenerationAndIndexing.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/main/java/org/carlspring/strongbox/repository/NpmRepositoryFeatures.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/cron/jobs/FetchChangesFeedCronJobTestIT.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/repository/NugetRepositoryFeatures.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-raw-layout-provider/src/test/java/org/carlspring/strongbox/providers/layout/RawLayoutProviderTest.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationControllerTestIT.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/raw/RawArtifactControllerTestIT.java
Labels: feature, in progress

#1139 TestArtifact annotation support
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/ArtifactManagementService.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/artifact/generator/ArtifactGenerator.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/artifact/generator/NullArtifactGenerator.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/storage/repository/RepositoryManagementTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/NullFileSystem.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/NullLayoutProvider.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/ArtifactManagementTestExecutionListener.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifact.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/RepositoryManagementTestExecutionListener.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementApplicationContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementContextSupport.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/io/ProxyFileSystemProvider.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/io/ProxyPathFileSystem.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/io/ProxyPathInvocationHandler.java
Labels: enhancement, feature, ready

#1152 issues/1142: fix Windows resource leaks
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementApplicationContext.java
Labels: ready

#1161 issues/1145: MavenArtifactGenerator implements ArtifactGenerator interface
  strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/ConfigurationManagementServiceImpl.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/storage/repository/RepositoryManagementTest.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryContext.java
  strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryManagementApplicationContext.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/configuration/MutableConfiguration.java
  strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/services/ConfigurationManagementService.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/MavenArtifactGenerator.java
  strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/MavenTestCaseWithArtifactGeneration.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/aql/AqlControllerTest.java
Labels: ready
